export const FETCH_USER_BALANCES = 'FETCH_USER_BALANCES';
export const FETCH_USER_BALANCES_SUCCEED = 'FETCH_USER_BALANCES_SUCCEED';
export const FETCH_USER_BALANCES_FAILED = 'FETCH_USER_BALANCES_FAILED';